service: mp-test-serverless

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    $ref: ./iamRoleStatements.json

functions:
  cleanup:
    handler: handler.cleanup
